parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: lifesmoother
    database_user: lifesmoother
    database_password: 
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 
    database_path: null
