<?php

namespace Gros\ComptaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DefaultsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DefaultsRepository extends EntityRepository
{
}
