parameters:
    google_charts_api_url: https://www.google.com/jsapi

services:
    gros_compta.charts:
        class: Gros\ComptaBundle\Service\GrosCharts
        arguments: [@doctrine, @security.context]

    gros_compta.parser:
        class: Gros\ComptaBundle\Service\GrosParser
        arguments: [@doctrine, @security.context, @gros.logger]

    gros_compta.paginator:
        class: Gros\ComptaBundle\Service\GrosPaginator
        arguments: [@doctrine, @security.context, %pagination_limit%]

    gros_compta.security:
        class: Gros\ComptaBundle\Service\GrosSecurity
        arguments: [@doctrine, @security.acl.provider, @security.context]

    gros.compta.admin.shops:
        class: Gros\ComptaBundle\Admin\ShopAdmin
        arguments: [null, Gros\ComptaBundle\Entity\Shop, 'SonataAdminBundle:CRUD']
        tags:
            - { name: sonata.admin, manager_type: orm, group: ComptaGros, label: Shops }

    gros.compta.admin.categories:
        class: Gros\ComptaBundle\Admin\CategoryAdmin
        arguments: [null, Gros\ComptaBundle\Entity\Category, 'SonataAdminBundle:CRUD']
        tags:
            - { name: sonata.admin, manager_type: orm, group: ComptaGros, label: Categories }

    gros.compta.admin.shoppers:
        class: Gros\ComptaBundle\Admin\ShopperAdmin
        arguments: [null, Gros\ComptaBundle\Entity\Shopper, 'SonataAdminBundle:CRUD']
        tags:
            - { name: sonata.admin, manager_type: orm, group: ComptaGros, label: Shoppers }

    gros.compta.admin.rules:
        class: Gros\ComptaBundle\Admin\RuleAdmin
        arguments: [null, Gros\ComptaBundle\Entity\Rule, 'SonataAdminBundle:CRUD']
        tags:
            - { name: sonata.admin, manager_type: orm, group: ComptaGros, label: Parsing Rules }

    gros.compta.admin.defaults:
        class: Gros\ComptaBundle\Admin\DefaultsAdmin
        arguments: [null, Gros\ComptaBundle\Entity\Defaults, 'SonataAdminBundle:CRUD']
        tags:
            - { name: sonata.admin, manager_type: orm, group: ComptaGros, label: Defaults }

    gros.logger:
        class: Symfony\Bridge\Monolog\Logger
        arguments: [gros]
        calls:
            - [pushHandler, [@gros.handler]]

    gros.handler:
        class: Monolog\Handler\StreamHandler
        # 200 = INFO, see Monolog::Logger for the values of log levels
        arguments: [%kernel.root_dir%/logs/%kernel.environment%.gros.log, 100]
