parameters:
#    gros_compta.example.class: Gros\Bundle\ComptaBundle\Example

services:
#    gros_compta.example:
#        class: %gros_compta.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
