parameters:
    google_charts_api_url: https://www.google.com/jsapi

services:
    gros_compta.charts:
        class: Gros\ComptaBundle\Service\GrosCharts
        arguments: [@doctrine]

    gros.compta.admin.shops:
        class: Gros\ComptaBundle\Admin\ShopAdmin
        arguments: [null, Gros\ComptaBundle\Entity\Shop, 'SonataAdminBundle:CRUD']
        tags:
            - { name: sonata.admin, manager_type: orm, group: ComptaGros, label: Shops }
