parameters:
    google_charts_api_url: https://www.google.com/jsapi

services:
    gros_compta.charts:
        class: Gros\ComptaBundle\Service\GrosCharts
        arguments: [@doctrine]

    gros_compta.parser:
        class: Gros\ComptaBundle\Service\GrosParser
        arguments: [@doctrine]

    gros.compta.admin.shops:
        class: Gros\ComptaBundle\Admin\ShopAdmin
        arguments: [null, Gros\ComptaBundle\Entity\Shop, 'SonataAdminBundle:CRUD']
        tags:
            - { name: sonata.admin, manager_type: orm, group: ComptaGros, label: Shops }

    gros.compta.admin.categories:
        class: Gros\ComptaBundle\Admin\CategoryAdmin
        arguments: [null, Gros\ComptaBundle\Entity\Category, 'SonataAdminBundle:CRUD']
        tags:
            - { name: sonata.admin, manager_type: orm, group: ComptaGros, label: Categories }

    gros.logger:
        class: Symfony\Bridge\Monolog\Logger
        arguments: [gros]
        calls:
            - [pushHandler, [@gros.handler]]

    gros.handler:
        class: Monolog\Handler\StreamHandler
        # 200 = INFO, see Monolog::Logger for the values of log levels
        arguments: [%kernel.root_dir%/logs/%kernel.environment%.gros.log, 100]
